# Generated by Django 5.2 on 2026-06-04 10:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('responder_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.TextField()),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('field', 'Field Enumerator'), ('analyst', 'Analyst'), ('supervisor', 'Supervisor')], max_length=50)),
                ('organization', models.CharField(blank=True, max_length=150, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrisisReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=255)),
                ('version_number', models.IntegerField(default=1)),
                ('is_latest', models.BooleanField(default=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_text', models.TextField(blank=True, null=True)),
                ('infrastructure_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('government', 'Government'), ('utility', 'Utility'), ('transport', 'Transport & Communication'), ('community', 'Community'), ('recreation', 'Public Recreation'), ('other', 'Other')], max_length=50)),
                ('infrastructure_name', models.CharField(blank=True, max_length=255, null=True)),
                ('affected_units', models.IntegerField(default=1)),
                ('nature_of_crisis', models.CharField(choices=[('earthquake', 'Earthquake'), ('flood', 'Flood'), ('tsunami', 'Tsunami'), ('cyclone', 'Cyclone/Hurricane'), ('wildfire', 'Wildfire'), ('explosion', 'Explosion'), ('conflict', 'Conflict'), ('civil_unrest', 'Civil Unrest'), ('chemical', 'Chemical Incident')], max_length=50)),
                ('damage_level', models.CharField(choices=[('minimal', 'Minimal'), ('partial', 'Partial'), ('complete', 'Complete')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('debris_clearing_needed', models.BooleanField(default=False)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('ai_damage_level', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('ai_description', models.TextField(blank=True, null=True)),
                ('submitter_token', models.CharField(blank=True, max_length=255, null=True)),
                ('submission_channel', models.CharField(blank=True, choices=[('web', 'Web'), ('mobile', 'Mobile'), ('whatsapp', 'WhatsApp'), ('offline', 'Offline')], max_length=50, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('es', 'Spanish'), ('ar', 'Arabic'), ('ru', 'Russian'), ('zh', 'Chinese')], default='en', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=50)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_by', models.UUIDField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('custom_responses', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='api.crisisreport')),
                ('previous_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='api.crisisreport')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.crisisreport')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to='api.responder')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.responder')),
            ],
        ),
    ]
