# Generated by Django 5.2 on 2026-06-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_update_crisisreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crisisreport',
            old_name='infrastructure_name',
            new_name='building_footprint_id',
        ),
        migrations.RenameField(
            model_name='crisisreport',
            old_name='debris_clearing_needed',
            new_name='debris',
        ),
        migrations.RenameField(
            model_name='crisisreport',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='crisisreport',
            old_name='longitude',
            new_name='lon',
        ),
        migrations.RemoveField(
            model_name='crisisreport',
            name='ai_confidence',
        ),
        migrations.RemoveField(
            model_name='crisisreport',
            name='ai_description',
        ),
        migrations.RemoveField(
            model_name='crisisreport',
            name='custom_responses',
        ),
        migrations.RemoveField(
            model_name='crisisreport',
            name='description',
        ),
        migrations.RemoveField(
            model_name='crisisreport',
            name='duplicate_of',
        ),
        migrations.RemoveField(
            model_name='crisisreport',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='crisisreport',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='crisisreport',
            name='is_duplicate',
        ),
        migrations.RemoveField(
            model_name='crisisreport',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='crisisreport',
            name='language',
        ),
        migrations.RemoveField(
            model_name='crisisreport',
            name='location_text',
        ),
        migrations.RemoveField(
            model_name='crisisreport',
            name='nature_of_crisis',
        ),
        migrations.RemoveField(
            model_name='crisisreport',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='crisisreport',
            name='previous_report',
        ),
        migrations.RemoveField(
            model_name='crisisreport',
            name='status',
        ),
        migrations.RemoveField(
            model_name='crisisreport',
            name='submission_channel',
        ),
        migrations.RemoveField(
            model_name='crisisreport',
            name='submitter_token',
        ),
        migrations.RemoveField(
            model_name='crisisreport',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='crisisreport',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='crisisreport',
            name='version_number',
        ),
        migrations.AddField(
            model_name='crisisreport',
            name='ai_damage_severity',
            field=models.CharField(blank=True, choices=[('little_or_no_damage', 'Little or no damage'), ('mild_damage', 'Mild damage'), ('severe_damage', 'Severe damage')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='crisisreport',
            name='ai_disaster_type',
            field=models.CharField(blank=True, choices=[('earthquake', 'Earthquake'), ('fire', 'Fire'), ('flood', 'Flood'), ('hurricane', 'Hurricane'), ('landslide', 'Landslide'), ('not_disaster', 'Not disaster'), ('other_disaster', 'Other')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='crisisreport',
            name='ai_humanitarian_category',
            field=models.CharField(blank=True, choices=[('affected_injured_or_dead_people', 'Affected/injured/dead people'), ('infrastructure_and_utility_damage', 'Infrastructure and utility damage'), ('not_humanitarian', 'Not humanitarian'), ('rescue_volunteering_or_donation_effort', 'Rescue/volunteering/donation effort')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='crisisreport',
            name='ai_informativeness',
            field=models.CharField(blank=True, choices=[('informative', 'Informative'), ('not_informative', 'Not informative')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='crisisreport',
            name='client_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='crisisreport',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crisisreport',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crisisreport',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crisisreport',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crisisreport',
            name='affected_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crisisreport',
            name='ai_damage_level',
            field=models.CharField(blank=True, choices=[('minimal', 'Minimal'), ('partial', 'Partial'), ('complete', 'Complete')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='crisisreport',
            name='damage_level',
            field=models.CharField(blank=True, choices=[('minimal', 'Minimal'), ('partial', 'Partial'), ('complete', 'Complete')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='crisisreport',
            name='infrastructure_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('government', 'Government'), ('utility', 'Utility'), ('transport', 'Transport & Communication'), ('community', 'Community'), ('recreation', 'Public Recreation'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='crisisreport',
            index=models.Index(fields=['building_footprint_id', 'is_latest'], name='api_crisisr_buildin_e24869_idx'),
        ),
        migrations.AddIndex(
            model_name='crisisreport',
            index=models.Index(fields=['ai_disaster_type'], name='api_crisisr_ai_disa_e404e5_idx'),
        ),
        migrations.AddIndex(
            model_name='crisisreport',
            index=models.Index(fields=['ai_damage_severity'], name='api_crisisr_ai_dama_1a0117_idx'),
        ),
        migrations.AddIndex(
            model_name='crisisreport',
            index=models.Index(fields=['-submitted_at'], name='api_crisisr_submitt_ba9a36_idx'),
        ),
    ]
