# Generated by Django 5.2 on 2026-06-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_infrastructure_name_crisisreport_building_footprint_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisisreport',
            name='location_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
