# Generated by Django 5.2 on 2026-06-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_crisisreport_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisisreport',
            name='nature_of_crisis',
            field=models.CharField(blank=True, choices=[('earthquake', 'Earthquake'), ('flood', 'Flood'), ('tsunami', 'Tsunami'), ('cyclone', 'Cyclone/Hurricane'), ('wildfire', 'Wildfire'), ('explosion', 'Explosion'), ('conflict', 'Conflict'), ('civil_unrest', 'Civil Unrest'), ('chemical', 'Chemical Incident'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
